name: create-release
on:
  push:
    branches:
      - "master"
      - "test"

jobs:
  create-release-x64:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
          include-prerelease: true

      - name: build
        run: | 
          dotnet publish -r linux-x64 -c Release -p:AssemblyName=ken-linux-x64 -p:DebugType=None -p:PublishSingleFile=true -p:PublishTrimmed=true --self-contained true
          dotnet publish -r linux-musl-x64 -c Release -p:AssemblyName=ken-linux-musl-x64 -p:DebugType=None -p:PublishSingleFile=true -p:PublishTrimmed=true --self-contained true
          dotnet publish -r linux-arm -c Release -p:AssemblyName=ken-linux-arm -p:DebugType=None -p:PublishSingleFile=true -p:PublishTrimmed=true --self-contained true
          dotnet publish -r linux-arm64 -c Release -p:AssemblyName=ken-linux-arm64 -p:DebugType=None -p:PublishSingleFile=true -p:PublishTrimmed=true --self-contained true
          #dotnet publish -r win-x64 -c Release -p:AssemblyName=ken-win-x64 -p:DebugType=None -p:PublishSingleFile=true -p:PublishTrimmed=true -p:IncludeNativeLibrariesInSingleFile=true --self-contained true
          #dotnet publish -r win-x86 -c Release -p:AssemblyName=ken-win-x86 -p:DebugType=None -p:PublishSingleFile=true -p:PublishTrimmed=true -p:IncludeNativeLibrariesInSingleFile=true --self-contained true
          #dotnet publish -r win-arm -c Release -p:AssemblyName=ken-win-arm -p:DebugType=None -p:PublishSingleFile=true -p:PublishTrimmed=true -p:IncludeNativeLibrariesInSingleFile=true --self-contained true
          #dotnet publish -r win-arm64 -c Release -p:AssemblyName=ken-win-arm64 -p:DebugType=None -p:PublishSingleFile=true -p:PublishTrimmed=true -p:IncludeNativeLibrariesInSingleFile=true --self-contained true
          #dotnet publish -r osx-x64 -c Release -p:AssemblyName=ken-osx-x64 -p:DebugType=None -p:PublishSingleFile=true -p:PublishTrimmed=true -p:IncludeNativeLibrariesInSingleFile=true --self-contained true
          #dotnet publish -r osx-arm64 -c Release -p:AssemblyName=ken-osx-arm64 -p:DebugType=None -p:PublishSingleFile=true -p:PublishTrimmed=true -p:IncludeNativeLibrariesInSingleFile=true --self-contained true


      - name: create-release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.CREATE_RELEASE_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "latest"
          files: |
            src/Cli/bin/Release/net5.0/linux-x64/publish/ken-linux-x64
            src/Cli/bin/Release/net5.0/linux-musl-x64/publish/ken-linux-musl-x64
            src/Cli/bin/Release/net5.0/linux-arm/publish/ken-linux-arm
            src/Cli/bin/Release/net5.0/linux-arm64/publish/ken-linux-arm64
            #src/Cli/bin/Release/net5.0/win-x64/publish/ken-win-x64.exe
            #src/Cli/bin/Release/net5.0/win-x86/publish/ken-win-x86.exe
            #src/Cli/bin/Release/net5.0/win-arm/publish/ken-win-arm.exe
            #src/Cli/bin/Release/net5.0/win-arm64/publish/ken-win-arm64.exe
            #src/Cli/bin/Release/net5.0/osx-x64/publish/ken-osx-x64
            #src/Cli/bin/Release/net5.0/osx-arm64/publish/ken-osx-arm64

      - name: push qiniu1
        run: |
          curl -L -o qrsctl https://devtools.qiniu.com/linux/amd64/qrsctl?ref=developer.qiniu.com

      - name: push qiniu2
        run: |
          ls
          pwd
          qrsctl login ${{ secrets.QN_USERNAME }} ${{ secrets.QN_PASSWORD }}
          qrsctl put -c kentxxq ken-linux-x64 src/Cli/bin/Release/net5.0/linux-x64/publish/ken-linux-x64
          qrsctl put -c kentxxq ken-linux-musl-x64 src/Cli/bin/Release/net5.0/linux-musl-x64/publish/ken-linux-musl-x64
          qrsctl put -c kentxxq ken-linux-arm src/Cli/bin/Release/net5.0/linux-arm/publish/ken-linux-arm
          qrsctl put -c kentxxq ken-linux-arm64 src/Cli/bin/Release/net5.0/linux-arm64/publish/ken-linux-arm64
          #qrsctl put -c kentxxq ken-win-x64.exe src/Cli/bin/Release/net5.0/win-x64/publish/ken-win-x64.exe
          #qrsctl put -c kentxxq ken-win-x86.exe src/Cli/bin/Release/net5.0/win-x86/publish/ken-win-x86.exe
          #qrsctl put -c kentxxq ken-win-arm.exe src/Cli/bin/Release/net5.0/win-arm/publish/ken-win-arm.exe
          #qrsctl put -c kentxxq ken-win-arm64.exe src/Cli/bin/Release/net5.0/win-arm64/publish/ken-win-arm64.exe
          #qrsctl put -c kentxxq ken-osx-x64 src/Cli/bin/Release/net5.0/osx-x64/publish/ken-osx-x64
          #qrsctl put -c kentxxq ken-osx-arm64 src/Cli/bin/Release/net5.0/osx-arm64/publish/ken-osx-arm64


