name: create-release
on:
  push:
    branches:
      - "master"
      - "test"

jobs:
  linux-x64-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
          include-prerelease: true

      - name: build
        run: | 
          dotnet publish -r linux-x64 -c Release -p:DebugType=None -p:PublishSingleFile=true -p:PublishTrimmed=true --self-contained true
          dotnet publish -r win-x64 -c Release -p:DebugType=None -p:PublishSingleFile=true -p:PublishTrimmed=true -p:IncludeNativeLibrariesInSingleFile=true --self-contained true
          dotnet publish -r osx-x64 -c Release -p:DebugType=None -p:PublishSingleFile=true -p:PublishTrimmed=true -p:IncludeNativeLibrariesInSingleFile=true --self-contained true


      - name: create-release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.CREATE_RELEASE_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "latest"
          files: |
            src/Cli/bin/Release/net5.0/linux-x64/publish/ken
            src/Cli/bin/Release/net5.0/win-x64/publish/ken
            src/Cli/bin/Release/net5.0/osx-x64/publish/ken